### PR TITLE
gh #230 L1 Issue fixes - dsAudio

### LINKED ISSUE #230: L1- SoC  - dsAudio
Fix issues found in [3.1.2](https://github.com/rdkcentral/rdk-halif-test-device_settings/milestone/4)

dsGetAudioPort_L1_negative - Fails due to wrong ASSERT usage.
dsSetAudioDelay_L1_positive - Fails due to setAudioDelay for headphone.  As per interface the required delay is set only with HDMI (ARC/eARC) and SPDIF.

### PR DESCRIPTION
**Pull request by akhilbhas**
* fix for the issues reported
Closes #230

### CODE REVIEW

**Review by srinivasgtl — COMMENTED** [review]
dsSetAudioDelay_L1_positive - need to consider the headphone changes as suggested by MTK.  As per our spec, the audio delay is only for HDMI ARC/EARC and spdiff.

please fix the above issue.

**Comment by akhilbhas** [comment]
> dsSetAudioDelay_L1_positive - need to consider the headphone changes as suggested by MTK. As per our spec, the audio delay is only for HDMI ARC/EARC and spdiff.
> 
> please fix the above issue.

Updated

**Review by srinivasgtl — APPROVED** [review]
ship it

**Review by srinivasgtl — APPROVED** [review]
ship it.

File: src/test_l1_dsAudio.c [hunk 1]
```diff
@@ -5495,16 +5495,23 @@ void test_l1_dsAudio_positive_dsSetAudioDelay(void)
         result = dsGetAudioPort(gDSAudioPortConfiguration[i].typeid, gDSAudioPortConfiguration[i].index, &handle);
         UT_ASSERT_EQUAL(result, dsERR_NONE);
         UT_ASSERT_NOT_EQUAL(handle, null_handle);
+        if(gDSAudioPortConfiguration[i].typeid != dsAUDIOPORT_TYPE_HEADPHONE)
```
Comment (bhanucbp) [inline src/test_l1_dsAudio.c:5498]: If there is another audio port which doesn't support delay will fail again. So, instead of adding check for headphone, add check for delay supported ports mentioned in header file
if(gDSAudioPortConfiguration[i].typeid == HDMI || gDSAudioPortConfiguration[i].typeid == ARC || gDSAudioPortConfiguration[i].typeid == SPDIF)

**Review by bhanucbp — COMMENTED** [review]
address review comment

**Review by bhanucbp — APPROVED** [review]
ship it
