### PR TITLE
gh #534 updated delay before getstatus for verify port

### LINKED ISSUE #534: Bug: dsHDMIIN dsCompositeIn L2 VerifyPortstatus wait for HAL to update active ports
### Problem/Opportunity

When execute L2 case VerifyHdmiInputPortStatus , VerifyPortSelectionAndStatus
The active port verification fails as the port doesnt gets updated in GetStatus. Its takes few seconds in HAL to update.
Inorder to handle that add sleep(2) 2sec so that the active port gets updated before querying from VTS

### Steps to reproduce

1. run VTS binary
2. execute L2 VerifyHdmiInputPortStatus, VerifyPortSelectionAndStatus
3. check if it gets passed

### Expected Behavior

Test should pass

### Actual Behavior

Test fails in the step to verify active port

### Notes (Optional)

_No response_

### PR DESCRIPTION
**Pull request by thanushreevani**
Updated L2 for dsHdmiin for verifyportstatus
Updated L2 for dsCompositeIn for verifyportstatus

### CODE REVIEW

File: src/test_l2_dsHdmiIn.c [hunk 1]
```diff
@@ -241,6 +242,7 @@ void test_l2_dsHdmiIn_VerifyHdmiInputPortStatus(void)
             continue;
         }
 
+	sleep(2);
         UT_LOG_DEBUG("Invoking dsHdmiInGetStatus()");
         ret = dsHdmiInGetStatus(&status);
```
[the remark this answers is not in the document]
Comment (kanjoe24) [reply src/test_l2_dsHdmiIn.c]: I would go with this suggestion from copilot. Let's go for a polling mechanism rather than sleep, that way slower platforms will take its own time and faster ones will update the status immediately.

Also, check the indentation.

**Review by kanjoe24 — COMMENTED** [review]
please check comment.

File: src/test_l2_dsHdmiIn.c [hunk 2]
```diff
@@ -241,8 +243,14 @@ void test_l2_dsHdmiIn_VerifyHdmiInputPortStatus(void)
             continue;
         }
 
-        UT_LOG_DEBUG("Invoking dsHdmiInGetStatus()");
-        ret = dsHdmiInGetStatus(&status);
+        for (uint8_t j = 1; j <= MAX_GETSTATUS_ATTEMPTS; j++)
+        {
+            UT_LOG_DEBUG("Invoking dsHdmiInGetStatus() attempt %d", j);
+            ret = dsHdmiInGetStatus(&status);
+            if (status.activePort == i)
```
Comment (kanjoe24) [inline src/test_l2_dsHdmiIn.c]: looks good.

Is it possible we name i to port or something easy to understand? 
Also, introduce braces here. https://github.com/rdkcentral/ut-core/wiki/1.1.-Standards:-Principles-from-Code-Complete#1-layout-and-formatting

Comment (thanushreevani) [reply src/test_l2_dsHdmiIn.c]: done

**Review by kanjoe24 — DISMISSED** [review]
approved.

File: src/test_l2_dsCompositeIn.c [hunk 3]
```diff
@@ -237,11 +240,19 @@ void test_l2_dsCompositeIn_VerifyCompositeInPortSelectionAndStatus(void)
...
-        if (ret != dsERR_NONE)
+        for (uint8_t j = 1; j <= MAX_GETSTATUS_ATTEMPTS; j++)
         {
-            UT_LOG_ERROR("Failed to get status of COMPOSITE Input ports\n");
+            UT_LOG_DEBUG("Invoking dsCompositeInGetStatus() attempt %d", j);
+            ret = dsCompositeInGetStatus(&status);
+            if (ret != dsERR_NONE)
+            {
+                UT_LOG_ERROR("Failed to get status of COMPOSITE Input ports\n");
+                continue;
```
Comment (kanjoe24) [inline src/test_l2_dsCompositeIn.c]: As copilot suggested do we need to add 1 more sleep before continue ? If yes, then add it in hdmi module as well.

Comment (thanushreevani) [reply src/test_l2_dsCompositeIn.c]: I feel not required because the continue is when the getstatus itself failed..

**Review by kanjoe24 — DISMISSED** [review]
Approved.

File: src/test_l2_dsHdmiIn.c [hunk 4]
```diff
@@ -241,10 +243,33 @@ void test_l2_dsHdmiIn_VerifyHdmiInputPortStatus(void)
             continue;
         }
 
-        UT_LOG_DEBUG("Invoking dsHdmiInGetStatus()");
-        ret = dsHdmiInGetStatus(&status);
-        UT_LOG_DEBUG("Active port: %d, Is presented: %d, Is port connected: %d, Return status: %d", status.activePort, status.isPresented, status.isPortConnected[i], ret);
-        UT_ASSERT_EQUAL(ret, dsERR_NONE);
+        dsError_t getstatus_ret = 0;
+        for (uint8_t j = 1; j <= MAX_GETSTATUS_ATTEMPTS; j++)
```
Comment (srinivasgtl) [inline src/test_l2_dsHdmiIn.c]: can we have a time based rather than the number of attempts based.  something like below

while (elapsed < timeoutMs)
    {
       UT_LOG_DEBUG("Invoking dsHdmiInGetStatus() attempt %d", j);
       getstatus_ret = dsHdmiInGetStatus(&status);
       UT_ASSERT_EQUAL(getstatus_ret, dsERR_NONE);
       // Break immediately on API failure
       if (getstatus_ret != dsERR_NONE) 
       {
          break;
       } 
       // Break if desired condition is met
       if (status.activePort == port_selected) 
       {
          break;
       }

        usleep(pollIntervalMs * 1000);
        elapsed += pollIntervalMs;
    }

Thanks

Comment (thanushreevani) [reply src/test_l2_dsHdmiIn.c]: done

**Review by srinivasgtl — APPROVED** [review]
approved

**Review by kanjoe24 — APPROVED** [review]
Approved.
