### PR TITLE
PR : gh #527 : Fix asserts and modify to UT_ASSERT

### LINKED ISSUE #527: Bug: Convert DS_ASSERT to UT_ASSERT instead of assert function
### Problem/Opportunity

Device Settings L3 is using assert function which terminates the test if the validation fails.
https://github.com/rdkcentral/rdk-halif-test-device_settings/blob/a183df91096e21a555cda1a715e72ffcfae605c8/src/test_l3_dsFPD.c#L81

https://github.com/search?q=repo%3Ardkcentral%2Frdk-halif-test-device_settings+DS_ASSERT&type=code

Solution:

Use UT_ASSERT instead of assert function.

### Steps to reproduce

Run VTS with run all option.

### Expected Behavior

All tests should run w/o crashing.

### Actual Behavior

Test crashes when the validation fails.

### Notes (Optional)

_No response_

### PR DESCRIPTION
**Pull request by kanjoe24**
This PR aligns the L3 Device Settings HAL tests with the UT testing framework by replacing direct use of the C assert macro with UT_ASSERT-based macros, and globally disables standard C assertions at build time.

Changes:

- Updated L3 test files to use DS_ASSERT/ASSERT macros mapped to UT_ASSERT instead of the C library assert.
- Replaced inline assert(status == dsERR_NONE) usages in test_l3_dsHost.c with DS_ASSERT(...) that now map to UT_ASSERT.
- Modified the top-level Makefile to add -DNDEBUG to KCFLAGS, disabling standard C assert in builds.

### CODE REVIEW

File: src/test_l3_dsCompositeIn.c [hunk 1]
```diff
@@ -79,7 +79,7 @@
 #include "test_parse_configuration.h"
 #include "dsCompositeIn.h"
 
-#define ASSERT assert
+#define ASSERT UT_ASSERT
```
Comment (srinivasgtl) [inline src/test_l3_dsCompositeIn.c]: to avoid confusion, lets follow the same nomenclature in all the codes. DS_ASSERT should be used instead of ASSERT

**Review by srinivasgtl — COMMENTED** [review]
please remove the assert.h in some files and one more comment.

File: src/test_l3_dsCompositeIn.c (hunk 1 above)
Comment (kanjoe24) [reply src/test_l3_dsCompositeIn.c]: Done

**Review by srinivasgtl — APPROVED** [review]
ship it.

**Review by bhanucbp — APPROVED** [review]
ship it
